title: Lochana Perera
url: "https://fivetwentythree.github.io"
baseurl: "/cv-blog"
remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://fivetwentythree.github.io"
footer_text: "Page design by Lochana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/cv-blog/"
 - name: "Projects"
   link: "projects"
 - name: "Blog"
   link: "blog"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
